name: Catalogue ADO fields

on:
  workflow_dispatch:

permissions:
  contents: write


jobs:
  catalogue-org-fields:
    runs-on: ubuntu-latest

    env:
      ADO_ORG: KKEU                    # hardcoded org
      ADO_PAT: ${{ secrets.ADO_PAT }}  # PAT in repo secrets

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ADO field catalogue
        run: |
          mkdir -p ado/outputs/${ADO_ORG}
          python ado/get_org_fields.py

      - name: Commit and push CSV if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add ado/outputs/

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update ADO field catalogue for ${ADO_ORG}"
            git push
            echo "::notice::Committed and pushed updated field catalogue for ${ADO_ORG}."
          fi
